file_name: ./saved_model/200_bn_no_age
data:
  data_root_dir: data/
  dir_to_scans: "/content/gdrive/My Drive/cs598_DL4H/ADNI_processed_200/subjects"
  dir_to_tsv: "/content/gdrive/My Drive/cs598_DL4H/ADNI_converted_meta_all/sample_200"
  batch_size: 4
  val_batch_size: 2
  workers: 1
  percentage_usage: 1.0
exp_name: 200_bn_no_age
visdom:
  port: 8064 
  server: null 
model:
  arch: ours
  input_channel: 1
  nhid: 512
  feature_dim: 1024
  n_label: 3
  expansion: 8
  num_blocks: 0
  type_name: conv3x3x3
  norm_type: Batch
adv_model:
  nhid: 36
  out_dim: 12
mmse_model:
  nhid: 64
training_parameters:
  use_age: False
  pretrain:  #dir to saved model here
  max_iter: 16000
  start_epoch: 0
  epochs: 30
  print_freq: 10
  max_grad_l2_norm:
  report_interval: 100
  snapshot_interval: 1000

optimizer:
  method: SGD
  par:
    lr: 0.01
    weight_decay: 0.000

